Repository buildkite/templates, pull requests merged in 2024-03, with the labels that each got.

#32 Add Snyk + Node.js template
  snyk/README.md
  snyk/example-project/package.json
  snyk/pipeline.yaml
Labels: Security

#79 Add AWS CDK template (using javascript)
  aws-cdk-javascript/README.md
  aws-cdk-javascript/example-project/.gitignore
  aws-cdk-javascript/example-project/.npmignore
  aws-cdk-javascript/example-project/README.md
  aws-cdk-javascript/example-project/bin/example-project.js
  aws-cdk-javascript/example-project/cdk.json
  aws-cdk-javascript/example-project/jest.config.js
  aws-cdk-javascript/example-project/lib/example-project-stack.js
  aws-cdk-javascript/example-project/package-lock.json
  aws-cdk-javascript/example-project/package.json
  aws-cdk-javascript/example-project/test/example-project.test.js
  aws-cdk-javascript/example-project/tsconfig.json
  aws-cdk-javascript/pipeline.yaml
  pulumi-aws/README.md
Labels: Infrastructure as code (IaC)

#86 Deploy docker image to Fly.io
  flyio-docker/README.md
  flyio-docker/example-project/Dockerfile
  flyio-docker/example-project/fly.toml
  flyio-docker/example-project/index.html
  flyio-docker/pipeline.yaml
  vercel-deploy/README.md
Labels: CD
